language: python

python:
  - "3.6"
  - "3.7"

cache: pip

# command to install dependencies
install:
  - pip install tensorflow
  - pip install keras
  - pip install -r requirements.txt

script:
  - pytest